# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "SF-TAP: Scalable and Flexible Traffic Analysis Platform"
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Now, you need not implement TCP reassembler, IP defragmenter, and flow separator.
  You just implement application level network traffic analyzers by using SF-TAP.
  SF-TAP allows you to easily develop your own analyzers, such as IDS, network forensics, and traffic engineering software.
  Enjoy your hacking!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  "SF-TAP"

# Build settings
markdown: kramdown
